//var ajax = new XMLHttpRequest();
//var parser = new DOMParser();
//var serializer = new XMLSerializer()

var entityIndexes = new Map();          // <String, Entity>
var locationsIndexes = new Map();       // <String, Location>
var cellsIndexes = new Map();           // <String, Cell>
var roomsIndexes = new Map();           // <String, Room>
var charactersIndexes = new Map();      // <String, Character>
var furnitureIndexes = new Map();       // <String, Furniture>
var itemsIndexes = new Map();           // <String, Item>
var keysIndexes = new Map();            // <String, Key>
var clothingIndexes = new Map();        // <String, Clothing>
var eventsIndexes = new Map();          // <String, GameEvent>
var characterMovements = new Map();     // <Character, Set<Room>>
var webPageIndexes = new Map();
var webSiteIndexes = new Map();
var agreeTOS = false;
var lastMenu = undefined;
//var enableAudio = false;
//var enableImages = true;
//var enableVideo = true;
var enableMinimap = true;
//var music = new Audio();
var currentTime = new Date("2017-07-03T17:35:00.000Z");
var previousTime = currentTime;
var eventsExecutedThisTick = new Set(); // Set of Events executed during the current Tick
var scenesViewedThisWindow = new Set(); // Set of Events executed during the current Room visit
var usePopups = false;
var interruptTick = false;

const speciesTypes = new Set(["fox","wolf","aardwolf","hyena","sheep","stoat","deer","rabbit","jackal","coyote","tiger","antelope","pig","horse"]);
//const bodyPartTypes = new Set(["head","eyes","leftEar","rightEar","nose","lips","tongue","neck","chest","torso","waist","groin","legs","feet"]);
const clothingTypes = new Set(["hat" ,"mask" ,"glasses" ,"earPiercingLeft" ,"earPiercingRight" ,"nosePiercing" ,"lipPiercing" ,"tonguePiercing" ,"collar" ,"neckwear" ,"shirt" ,"jacket" ,"belt" ,"gloves" ,"underwear" ,"pants" ,"socks" ,"shoes" ,"bra"]);
const handTypes = new Set(["fur", "pad", "hoof", "clovenhoof", "skin"]);
const feetTypes = handTypes;
const eyeTypes = new Set(["circle", "slit", "rectangle"]);
const peltTypes = new Set(["skin", "fur", "wool", "hair"]);
const roomTypes = new Set(["hallway", "lobby", "bedroom", "livingroom", "bathroom", "kitchen", "diningroom", "closet", "basement", "extBuilding", "street", "walkway", "lot"]);
const furnitureTypes = new Set(["chair","recliner","loveseat","couch","bed","table","desk","shelf","cupboard","cabinet","bureau","hook","tv","fridge","oven","microwave","toaster","tub","shower","sink","toilet","mirror","basket"]);
const actionTypes = new Set(["move","use","sit","lay","sleep","open","put","give","take","remove","hold","wear","look","talk","sex","attack","rape","stand","walk","follow","stay","masturbate"]);
